# Generated by Django 2.0.3 on 2018-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('bpm', models.IntegerField(verbose_name='bpm')),
                ('img', models.FileField(upload_to='logos/', verbose_name='Изображение')),
                ('mp3File', models.FileField(upload_to='tracks/mp3/', verbose_name='Файл mp3')),
                ('wavFile', models.FileField(upload_to='tracks/wav/', verbose_name='Файл wav')),
                ('flpFile', models.FileField(upload_to='tracks/flp/', verbose_name='Файл flp')),
                ('mp3Cost', models.IntegerField(verbose_name='Цена mp3')),
                ('wavCost', models.IntegerField(verbose_name='Цена wav')),
                ('flpCost', models.IntegerField(verbose_name='Цена flp')),
                ('mwCost', models.IntegerField(verbose_name='Цена mp3+wav')),
                ('mfCost', models.IntegerField(verbose_name='Цена mp3+flp')),
                ('wfCost', models.IntegerField(verbose_name='Цена wav+flp')),
                ('fullCost', models.IntegerField(verbose_name='Цена mp3+wav+flp')),
            ],
        ),
    ]
